# Generated by Django 4.2.11 on 2024-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart_order_product_orderitem_order_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
    ]
